service: p3-iam-permissions

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: serverless-admin
  region: us-east-1
  # you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:*"
          Resource:
            - "*"

functions:
  listFunctions:
    handler: handler.listFunctions
